---

- name: If on a Red Hat-based system, upgrade using dnf
  import_tasks: update-using-dnf.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: If on a Debian-based system, upgrade using apt
  import_tasks: update-using-apt.yml
  when: ansible_facts['os_family'] == 'Debian'
