---

- name: Update systems that use DNF
  import_tasks: update-using-dnf.yml
  when: ansible_facts['pkg_mgr'] == 'dnf'

- name: Update systems that use APT
  import_tasks: update-using-apt.yml
  when: ansible_facts['pkg_mgr'] == 'apt'
