---

- name: Update systems that use DNF
  import_tasks: update-using-dnf.yml
  when: ansible_facts['os_family'] == 'RedHat'

- name: Update systems that use APT
  import_tasks: update-using-apt.yml
  when: ansible_facts['os_family'] == 'Debian'
