---

- name: Update the system
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Check if a reboot is required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file

- name: Reboot the system if required
  ansible.builtin.reboot:
  become: true
  when: reboot_required_file.stat.exists
