---

- name: Install packages required for ansible.builtin.dnf
  ansible.builtin.dnf:
    name: python3-dnf
    update_cache: true
  become: true

- name: Update all packages using DNF
  ansible.builtin.dnf:
    name: "*"
    state: latest
    update_cache: true
  become: true

- name: Clean up packages using DNF
  ansible.builtin.dnf:
    autoremove: true
  become: true

- name: Check if a reboot is required for DNF systems
  ansible.builtin.command:
    cmd: dnf needs-restarting -r
  register: reboot_required
  changed_when: reboot_required.rc == 1
  failed_when: (reboot_required.rc != 0) and (reboot_required.rc != 1)

- name: Reboot DNF systems that require a reboot
  ansible.builtin.reboot:
  become: true
  when: reboot_required.rc == 1
